language: c

compiler: gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "acMNCaXMTnR2/mGm52Bijwr1Q9XnNYeguLOg5pWDXNYs2/hOreOFqlixgzP+O1yfn3muD054qKZIVzxGfiyA0QQNL7LBDhEChcM0uvXrjdL++74UW6MAJh5v0EkX7mA3Adjy/nokMtdtMiMEdDICsV1c20iZPdIeSVKqFuOpCJY="

install: 
  - sudo apt-get update -qq
  - sudo apt-get install cscope exuberant-ctags

script:
  - make package

addons:
  coverity_scan:
    project:
      name: "billy482/tape-benchmark"
      description: "Build submitted via Travis CI"
    notification_email: clercin.guillaume@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan
